feat: reducing moment timezone timezones
zextras/carbonio-ui-sdk pull request #12
Opened 2023-02-09 09:15 UTC by nubsthead

2023-02-09 09:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Zextras/carbonio-ui-sdk?pullRequest=12) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Zextras/carbonio-ui-sdk?pullRequest=12) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Zextras/carbonio-ui-sdk?pullRequest=12) it.</sub>

2023-02-24 08:42 UTC, Gammax92 approved these changes

2023-03-09 08:18 UTC, gnekoz approved these changes

2023-03-10 09:03 UTC, beawar requested changes
I think an additional improvement could be set moment-timezone as external dependency as moment is (and install it inside the shell), so that this module is bundle only one time inside the shell. But this could be a step 2 (we should check with Smoky(@CerDennis @lisaparma @yukiLu6) if this is a viable proposal)

2023-03-10 09:03 UTC, beawar commented on package.json
> +    "moment-timezone-data-webpack-plugin": "^1.5.1",
This dependency must be listed inside the dependencies (not devDep) because otherwise when installing the package, the dependency is not installed with the sdk itself and npm throw the error `Error: Cannot find module 'moment-timezone-data-webpack-plugin'`

2023-03-10 09:03 UTC, beawar commented on scripts/utils/matchzones.js
> +export const matchZones = [
wrong syntax. You should export using `module.exports = { matchZones }` or `exports.matchZones = `.

the object returned by the require here https://github.com/Zextras/carbonio-ui-sdk/blob/91a71e7f28bd7c5b21dd0ff25931a18006e9b651/scripts/configs/webpack.build.config.js#L20 is the one exported with one of the two syntax reported before.
 
throw Error
```
export const matchZones = [
^^^^^^
SyntaxError: Unexpected token 'export'
```

2023-03-10 13:57 UTC, beawar approved these changes

2023-03-15 09:36 UTC, lisaparma approved these changes

2023-03-17 08:59 UTC, CerDennis commented
Following the info from @AlessioCrestani let's wait to understand if this pr is still necessary
"about the timezone topic: I've discussed with Luca Arcara and probably we can manage missing timezone on the backend side, so the PR from Garbiele is on stand-by"

2023-03-23 14:28 UTC, lisaparma commented
As decided in the Frontend Tribe this PR is no more useful. This issue will be resolved from backend.

2023-03-23 14:28 UTC, closed without merging