ci: add jenkins pipeline
zextras/carbonio-ui-sdk pull request #15
Opened 2023-03-15 14:47 UTC by CerDennis

2023-03-16 14:10 UTC, beawar requested changes

2023-03-16 14:10 UTC, beawar commented on Jenkinsfile
> +        stage("Build") {
build stage can/must be removed because the package does not have a build script, and does not need to be built (for now at least) -> build is failing because there is no build script inside the package.json

2023-03-17 09:24 UTC, beawar approved these changes

2023-03-27 14:03 UTC, lisaparma approved these changes

2023-03-29 10:09 UTC, merged